const fs = require('fs')
if (!fs.existsSync('./logs')) fs.mkdirSync('./logs')
if (!fs.existsSync('./.env')) fs.writeFileSync('./.env', 'BOT_TOKEN=""\nAPI_KEY=""')
if (!fs.existsSync('./history.json')) fs.writeFileSync('./history.json', '')
if (!fs.existsSync('./allowed_channels.json')) fs.writeFileSync('./allowed_channels.json', '{}')
if (!fs.existsSync('./blocked_channels.json')) fs.writeFileSync('./blocked_channels.json', '{}')
if (!fs.existsSync('./allowed_users.json')) fs.writeFileSync('./allowed_users.json', '{}')
if (!fs.existsSync('./blocked_users.json')) fs.writeFileSync('./blocked_users.json', '{}')
if (!fs.existsSync('./default_history.json')) fs.writeFileSync('./default_history.json', '[]')
require('./logger')
